### ISSUE TITLE
Not working with Jquery version 3.1.1

### ISSUE THREAD

**Issue by pdg6805** [peterhry/CircleType#17]
I'm trying to make it work with Jquery version 3.1.1, and its throwing an error `TypeError: a.indexOf is not a function` when passing in a collection selection.

it appears the the issue is with the event handling, that you use `.load` and `.resize` Ill submit a pull request with a update

**Comment by peterhry** [comment]
pull request merged
https://github.com/peterhry/CircleType/pull/18
